In [2]:
import pandas as pd
import numpy as np


In [3]:
df = pd.read_csv("Student_performance_data _.csv")
df

StudentID  Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  \
0          1001   17       1          0                  2        19.833723   
1          1002   18       0          0                  1        15.408756   
2          1003   15       0          2                  3         4.210570   
3          1004   17       1          0                  3        10.028829   
4          1005   17       1          0                  2         4.672495   
...         ...  ...     ...        ...                ...              ...   
2387       3388   18       1          0                  3        10.680555   
2388       3389   17       0          0                  1         7.583217   
2389       3390   16       1          0                  2         6.805500   
2390       3391   16       1          1                  0        12.416653   
2391       3392   16       1          0                  2        17.819907   

      Absences  Tutoring  ParentalSupport  Extracurricular  Sports  Music  \
0            7         1                2                0       0      1   
1            0         0                1                0       0      0   
2           26         0                2                0       0      0   
3           14         0                3                1       0      0   
4           17         1                3                0       0      0   
...        ...       ...              ...              ...     ...    ...   
2387         2         0                4                1       0      0   
2388         4         1                4                0       1      0   
2389        20         0                2                0       0      0   
2390        17         0                2                0       1      1   
2391        13         0                2                0       0      0   

      Volunteering       GPA  GradeClass  
0                0  2.929196         2.0  
1                0  3.042915         1.0  
2                0  0.112602         4.0  
3                0  2.054218         3.0  
4                0  1.288061         4.0  
...            ...       ...         ...  
2387             0  3.455509         0.0  
2388             0  3.279150         4.0  
2389             1  1.142333         2.0  
2390             0  1.803297         1.0  
2391             1  2.140014         1.0  

[2392 rows x 15 columns]

In [4]:
df.isna().sum()#first step is to check null values

StudentID            0
Age                  0
Gender               0
Ethnicity            0
ParentalEducation    0
StudyTimeWeekly      0
Absences             0
Tutoring             0
ParentalSupport      0
Extracurricular      0
Sports               0
Music                0
Volunteering         0
GPA                  0
GradeClass           0
dtype: int64

In [5]:
#secound step is to check data types and convert then into same data type
df[["StudyTimeWeekly","GPA","GradeClass"]]= df[["StudyTimeWeekly","GPA","GradeClass"]].astype(int)
df.dtypes

StudentID            int64
Age                  int64
Gender               int64
Ethnicity            int64
ParentalEducation    int64
StudyTimeWeekly      int64
Absences             int64
Tutoring             int64
ParentalSupport      int64
Extracurricular      int64
Sports               int64
Music                int64
Volunteering         int64
GPA                  int64
GradeClass           int64
dtype: object

In [6]:
df

StudentID  Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  \
0          1001   17       1          0                  2               19   
1          1002   18       0          0                  1               15   
2          1003   15       0          2                  3                4   
3          1004   17       1          0                  3               10   
4          1005   17       1          0                  2                4   
...         ...  ...     ...        ...                ...              ...   
2387       3388   18       1          0                  3               10   
2388       3389   17       0          0                  1                7   
2389       3390   16       1          0                  2                6   
2390       3391   16       1          1                  0               12   
2391       3392   16       1          0                  2               17   

      Absences  Tutoring  ParentalSupport  Extracurricular  Sports  Music  \
0            7         1                2                0       0      1   
1            0         0                1                0       0      0   
2           26         0                2                0       0      0   
3           14         0                3                1       0      0   
4           17         1                3                0       0      0   
...        ...       ...              ...              ...     ...    ...   
2387         2         0                4                1       0      0   
2388         4         1                4                0       1      0   
2389        20         0                2                0       0      0   
2390        17         0                2                0       1      1   
2391        13         0                2                0       0      0   

      Volunteering  GPA  GradeClass  
0                0    2           2  
1                0    3           1  
2                0    0           4  
3                0    2           3  
4                0    1           4  
...            ...  ...         ...  
2387             0    3           0  
2388             0    3           4  
2389             1    1           2  
2390             0    1           1  
2391             1    2           1  

[2392 rows x 15 columns]

In [7]:
df.drop(labels=["StudentID","Age","Gender"], axis=1, inplace=True)
#third step is to drop unnecesary columns

In [8]:
df

Ethnicity  ParentalEducation  StudyTimeWeekly  Absences  Tutoring  \
0             0                  2               19         7         1   
1             0                  1               15         0         0   
2             2                  3                4        26         0   
3             0                  3               10        14         0   
4             0                  2                4        17         1   
...         ...                ...              ...       ...       ...   
2387          0                  3               10         2         0   
2388          0                  1                7         4         1   
2389          0                  2                6        20         0   
2390          1                  0               12        17         0   
2391          0                  2               17        13         0   

      ParentalSupport  Extracurricular  Sports  Music  Volunteering  GPA  \
0                   2                0       0      1             0    2   
1                   1                0       0      0             0    3   
2                   2                0       0      0             0    0   
3                   3                1       0      0             0    2   
4                   3                0       0      0             0    1   
...               ...              ...     ...    ...           ...  ...   
2387                4                1       0      0             0    3   
2388                4                0       1      0             0    3   
2389                2                0       0      0             1    1   
2390                2                0       1      1             0    1   
2391                2                0       0      0             1    2   

      GradeClass  
0              2  
1              1  
2              4  
3              3  
4              4  
...          ...  
2387           0  
2388           4  
2389           2  
2390           1  
2391           1  

[2392 rows x 12 columns]

In [9]:
#identifying the fetures and target columns
# X = fetures
# y = target
x = df.iloc[:,:-1]
y = df.iloc[:,-1]
y

0       2
1       1
2       4
3       3
4       4
       ..
2387    0
2388    4
2389    2
2390    1
2391    1
Name: GradeClass, Length: 2392, dtype: int64

In [10]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
#creating an object for the class MIN max scaler
scaler.fit(x)#fetures values simlier range 0-1 #chil case il values thamil ul difference veluthayirikum eg(2,40,4,60,120),
#ithupole ula data vech cheythal acuraccy valare kurav ayirikum ,
#so aa prshnm solve cheyan min max scaler use cheyyum ,ithupole kure methods und ath solve cheyan ivide use cheyunath minmax scaler aanu\
#it orginal data kk currespondent ayittula 0-1 range il data convert cheyyum
x_scaled = scaler.transform(x)
x_scaled
#these are the steps of feature scaling
#it is the first step in ML model building after preparing the data

array([[0.        , 0.5       , 1.        , ..., 1.        , 0.        ,
        0.5       ],
       [0.        , 0.25      , 0.78947368, ..., 0.        , 0.        ,
        0.75      ],
       [0.66666667, 0.75      , 0.21052632, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.5       , 0.31578947, ..., 0.        , 1.        ,
        0.25      ],
       [0.33333333, 0.        , 0.63157895, ..., 1.        , 0.        ,
        0.25      ],
       [0.        , 0.5       , 0.89473684, ..., 0.        , 1.        ,
        0.5       ]], shape=(2392, 11))

In [ ]:
# dividing the data into training and testing data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_scaled,y,test_size=0.2) 
# ------------------------------------------------------------  
#x_train = 80% training data(features)
#x_test = 20% testing data(features)
#y_train = 80% training data(target)
#y_test = 20% testing data(target)
# ------------------------------------------------------------
#size tells the how it should take for the testing purpose,
# Here it takes 20% testing (which is we specified like (0.2),(0,3)means 30% for testing purpose (0.5) means 50% for testing purpose) and 80% for training purpose

SyntaxError: expected argument value expression (3533776140.py, line 3)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
#here the model default value for n_neighbors is 5(this is the odd number we take)
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
y_pred = knn.predict(x_test)
y_pred

array([1, 3, 4, 4, 4, 3, 4, 4, 2, 4, 2, 2, 1, 2, 2, 1, 0, 4, 4, 4, 1, 4,
       3, 4, 4, 3, 4, 2, 1, 4, 4, 1, 4, 4, 2, 2, 2, 2, 4, 3, 4, 3, 4, 4,
       1, 4, 4, 4, 2, 0, 3, 4, 4, 4, 2, 0, 4, 4, 2, 1, 2, 2, 4, 4, 1, 3,
       4, 4, 2, 4, 4, 2, 3, 4, 3, 4, 2, 4, 4, 1, 4, 2, 2, 4, 4, 4, 4, 4,
       3, 4, 2, 4, 1, 4, 2, 0, 3, 2, 4, 4, 3, 3, 1, 4, 4, 3, 3, 1, 4, 3,
       4, 1, 4, 3, 4, 4, 4, 2, 3, 4, 2, 4, 3, 4, 3, 4, 3, 4, 2, 2, 4, 2,
       2, 4, 0, 4, 2, 4, 2, 4, 3, 4, 3, 2, 2, 4, 3, 4, 4, 3, 1, 1, 2, 3,
       4, 1, 4, 4, 4, 4, 2, 1, 4, 4, 2, 4, 1, 2, 4, 4, 4, 1, 2, 4, 2, 4,
       4, 1, 1, 4, 4, 2, 4, 0, 4, 4, 4, 3, 2, 4, 4, 4, 4, 4, 3, 3, 2, 1,
       0, 4, 2, 4, 2, 4, 1, 1, 1, 4, 4, 3, 3, 2, 0, 2, 4, 4, 2, 2, 4, 4,
       4, 4, 1, 0, 4, 1, 4, 4, 1, 1, 4, 3, 1, 4, 4, 1, 4, 4, 4, 2, 1, 4,
       3, 2, 4, 1, 4, 4, 4, 1, 4, 4, 3, 2, 4, 4, 3, 3, 4, 1, 3, 4, 4, 4,
       4, 1, 4, 4, 1, 2, 4, 4, 4, 3, 2, 4, 1, 3, 4, 4, 4, 3, 4, 4, 4, 4,
       2, 1, 1, 2, 4, 4, 3, 4, 2, 4, 1, 1, 1, 4, 2,

In [ ]:
y_test.values

array([1, 2, 4, 4, 3, 0, 4, 4, 3, 4, 3, 2, 1, 2, 3, 1, 1, 4, 3, 4, 1, 4,
       2, 4, 4, 0, 4, 2, 2, 4, 4, 1, 4, 4, 2, 2, 3, 3, 4, 2, 4, 3, 4, 4,
       1, 3, 4, 4, 3, 3, 3, 4, 3, 4, 4, 1, 4, 4, 1, 1, 2, 3, 4, 4, 1, 2,
       2, 4, 2, 4, 4, 2, 2, 4, 2, 4, 2, 4, 4, 0, 4, 3, 2, 4, 4, 4, 4, 4,
       3, 4, 2, 4, 1, 4, 2, 1, 3, 1, 4, 4, 3, 4, 3, 4, 4, 0, 1, 2, 4, 2,
       4, 0, 4, 3, 4, 4, 4, 3, 3, 4, 2, 2, 4, 4, 1, 4, 3, 4, 3, 4, 4, 0,
       4, 4, 0, 4, 2, 4, 2, 2, 3, 4, 4, 2, 3, 4, 3, 4, 4, 3, 3, 0, 2, 4,
       4, 1, 4, 3, 4, 4, 3, 0, 4, 1, 2, 4, 0, 2, 4, 2, 4, 1, 4, 4, 3, 4,
       4, 1, 1, 4, 4, 2, 4, 0, 1, 4, 4, 2, 3, 4, 4, 4, 4, 4, 3, 2, 2, 0,
       3, 4, 2, 4, 1, 4, 3, 2, 0, 4, 4, 2, 2, 2, 0, 2, 4, 4, 1, 2, 4, 4,
       4, 4, 2, 4, 4, 1, 4, 4, 1, 3, 4, 4, 1, 4, 4, 0, 4, 4, 4, 2, 1, 4,
       2, 2, 4, 1, 4, 4, 4, 3, 4, 4, 4, 1, 4, 1, 3, 2, 4, 2, 3, 4, 4, 4,
       0, 0, 4, 4, 2, 3, 4, 3, 4, 2, 1, 4, 3, 4, 4, 4, 4, 3, 1, 0, 4, 4,
       2, 0, 0, 3, 4, 4, 2, 4, 4, 4, 4, 1, 0, 4, 4,

In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))
#0.6617954070981211 :: 66% is the accurace of this model
#it changes every time because of the random state

0.6680584551148225
