In [79]:
import pandas as pd
import numpy as np

In [80]:
df = pd.read_csv("loan_approval.csv")
df

name              city  income  credit_score  loan_amount  \
0        Allison Hill         East Jill  113810           389        39698   
1        Brandon Hall     New Jamesside   44592           729        15446   
2        Rhonda Smith      Lake Roberto   33278           584        11189   
3     Gabrielle Davis  West Melanieview  127196           344        48823   
4        Valerie Gray         Mariastad   66048           496        47174   
...               ...               ...     ...           ...          ...   
1995   James Schaefer         Robertton   92163           770        12251   
1996        Diana Lin         New Frank   38799           635        48259   
1997    Brandon Meyer        East Haley   41957           763        16752   
1998      Jason Price          Adamland  139022           360        24031   
1999     Nicole Brown    New Nathantown   41188           482        31397   

      years_employed  points  loan_approved  
0                 27    50.0          False  
1                 28    55.0          False  
2                 13    45.0          False  
3                 29    50.0          False  
4                  4    25.0          False  
...              ...     ...            ...  
1995              13    85.0           True  
1996              17    40.0          False  
1997               5    60.0           True  
1998              35    55.0          False  
1999               6    20.0          False  

[2000 rows x 8 columns]

In [81]:
df.isna().sum()
df.dtypes


name               object
city               object
income              int64
credit_score        int64
loan_amount         int64
years_employed      int64
points            float64
loan_approved        bool
dtype: object

In [82]:
df.drop(labels=(["name","city"]),axis=1,inplace=True)

In [83]:
df

income  credit_score  loan_amount  years_employed  points  loan_approved
0     113810           389        39698              27    50.0          False
1      44592           729        15446              28    55.0          False
2      33278           584        11189              13    45.0          False
3     127196           344        48823              29    50.0          False
4      66048           496        47174               4    25.0          False
...      ...           ...          ...             ...     ...            ...
1995   92163           770        12251              13    85.0           True
1996   38799           635        48259              17    40.0          False
1997   41957           763        16752               5    60.0           True
1998  139022           360        24031              35    55.0          False
1999   41188           482        31397               6    20.0          False

[2000 rows x 6 columns]

In [84]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["loan_approved"] = le.fit_transform(df["loan_approved"])

In [85]:
x = df.iloc[:,:-1]
x
y = df.iloc[:,-1]
y

0       0
1       0
2       0
3       0
4       0
       ..
1995    1
1996    0
1997    1
1998    0
1999    0
Name: loan_approved, Length: 2000, dtype: int64

In [86]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_scaled = scaler.fit_transform(x)
x_scaled

array([[0.69849305, 0.16181818, 0.78967679, 0.675     , 0.44444444],
       [0.12124826, 0.78      , 0.29450558, 0.7       , 0.5       ],
       [0.02689495, 0.51636364, 0.20758723, 0.325     , 0.38888889],
       ...,
       [0.09927363, 0.84181818, 0.32117116, 0.125     , 0.55555556],
       [0.90874899, 0.10909091, 0.46979194, 0.875     , 0.5       ],
       [0.09286054, 0.33090909, 0.62018907, 0.15      , 0.11111111]],
      shape=(2000, 5))

In [87]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_scaled,y,test_size=0.2,random_state=42)

In [88]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [89]:
y_pred = knn.predict(x_test)
y_pred

array([0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,

In [90]:
y_test.values

array([0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,

In [91]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_pred,y_test))

0.9675
